---

- hosts: localhost
  become: true
  tasks:
   
  - name: install google repo key
    apt_key:
     url: https://dl-ssl.google.com/linux/linux_signing_key.pub

  - name: add google repo
    apt_repository:
     repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
     filename: google-chrome

  - name: update repos
    apt:
     update_cache: yes

  - name: upgrade packages
    apt:
     upgrade: dist

  - name: install snap package manager
    apt:
     name: snapd
     state: latest
  
  - name: install google chrome
    apt: 
     name: google-chrome-stable
     state: latest

  - name: install zoom client
    apt:
     deb: https://zoom.us/client/latest/zoom_amd64.deb

  - name: install vlc media player
    apt:
     name: vlc
     state: latest
  
  - name: install opensc
    apt:
     name: opensc
 
  - name: install unzip
    apt:
     name: unzip
     state: latest

  - name: install libreoffice
    apt:
     name: libreoffice
     state: latest
     
  - name: install slack from snap store
    snap:
     name: slack
     classic: yes

  - name: install spotify from snap store
    snap:
     name: spotify

  - name: install nmap
    apt:
     name: nmap
     state: latest

  - name: install net-tools
    apt:
     name: net-tools
     state: latest

  - name: copy ssh configs 
    copy:
     src: thor
     dest: /home/sachinp/.ssh/
     owner: sachinp

  - name: rename ssh key
    command: "mv /home/sachinp/.ssh/thor /home/sachinp/.ssh/id_rsa.pub"
  
  - name: copy ssh configs 
    copy:
     src: loki
     dest: /home/sachinp/.ssh/
     owner: sachinp

  - name: rename ssh key
    command: "mv /home/sachinp/.ssh/loki /home/sachinp/.ssh/id_rsa"

  - name: copy ssh configs 
    copy:
     src: config
     dest: /home/sachinp/.ssh/
     owner: sachinp

  - name: copy bash profile
    copy:
     src: .bashrc
     dest: /home/sachinp/
     owner: sachinp

  - name: copy anyconnect installer
    copy:
     src: anyconnect-linux64-4.9.04053.zip
     dest: /home/sachinp/
     owner: sachinp

  - name: unzip anyconnect installer
    unarchive:
     src: /home/sachinp/anyconnect-linux64-4.9.04053.zip
     dest: /home/sachinp/
     owner: sachinp
     mode: 0700

  - name: install anyconnect
    command: "sudo /home/sachinp/anyconnect-linux64-4.9.04053/vpn/vpn_install.sh"
    

    
     
